server:
  port: 0
  servlet:
    context-path: /api/v1

spring:
  jackson:
    default-property-inclusion: non_null
  messages:
    use-code-as-default-message: true
    basename: messages/messages
    fallback-to-system-locale: false
    encoding: UTF-8
  mvc:
    format:
      date: iso
