eureka:
  instance:
    instanceId: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    should-enforce-registration-at-init: true
