eureka:
  instance:
    instanceId: ${spring.application.name}:${random.uuid}
    hostname: ${HOST_NAME:localhost}
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    should-enforce-registration-at-init: true
