server:
  port: 0
  servlet:
    context-path: /api/v1

spring:
  cloud:
    config:
      allow-override: true
      #override-none: true
      override-system-properties: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
  messages:
    use-code-as-default-message: true
    basename: messages/messages
    fallback-to-system-locale: false
    encoding: UTF-8
  mvc:
    format:
      date: iso

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.uuid}

springdoc:
  api-docs:
    path: /api-docs
